---
- name: include task specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - 'default.yml'
      paths: '../vars'

- block:
  - name: Ensure that selinux is enabled
    command: getenforce
    register: result
    ignore_errors: true
    changed_when: false

  - name: Grant selinux permission for Ngnix
    seboolean:
      name: '{{item}}'
      persistent: yes
      state: True
    with_items:
      - httpd_can_network_connect
    when: 'result|success and result.stdout.lower() != "disabled"'

  - name: Install nginx.conf for Nginx
    copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
      backup: yes

  - name: Install ketchup.conf for Ngnix
    template:
      src: 'ketchup.conf.j2'
      dest: '{{ nginx_conf_dir }}/ketchup.conf'
    notify:
      - restart nginx

  become: true

